language: go

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover
before_script:
  - golint ./... | xargs -r false

script:
- ./go_test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)